-- Renames three fields from S3-specific names to a storage-agnostic name,
-- following the decision to use Netlify Blobs instead of S3 (see
-- PROGRESS.md decision log). Written as RENAME COLUMN rather than the
-- drop-and-recreate Prisma generated by default (which cannot detect renames
-- non-interactively) -- no real data exists in these tables yet, but a
-- rename is the correct migration regardless and would not have broken had
-- rows already existed.

ALTER TABLE "documents" RENAME COLUMN "s3Key" TO "storageKey";
ALTER TABLE "payout_batches" RENAME COLUMN "bankFileS3Key" TO "bankFileStorageKey";
ALTER TABLE "payout_lines" RENAME COLUMN "statementS3Key" TO "statementStorageKey";
